name: Build

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
           node-version: 20
      
        
          
   

      - name: Build Project
        run: npm run build
