name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2


        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
           node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      
        
          
   

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: ./build
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}





        

        
